In [2]:
from scipy.ndimage import correlate

In [3]:
import numpy as np


In [4]:
correlate(np.arange(10),[1,2.5])

array([ 0,  2,  6,  9, 13, 16, 20, 23, 27, 30])

In [5]:
## cross shaped kernel

In [6]:
footprint=np.array([[0,1,0],[1,1,1],[0,1,0]])

In [7]:
footprint

array([[0, 1, 0],
       [1, 1, 1],
       [0, 1, 0]])

In [8]:
from scipy.ndimage import correlate1d

In [9]:
a=[0,0,0,1,0,0,0]

In [10]:
correlate1d(a,[1,1,1])

array([0, 0, 1, 1, 1, 0, 0])