In [5]:
import numpy as np
from scipy.linalg import solve_triangular
import pandas as pd
from scipy import linalg
import seaborn as sns


[[1 2]
 [4 5]]
-3.0


In [6]:
#determinant
a=np.array([[1,2],[4,5]])
print(a)
print(linalg.det(a))



[[1 2]
 [4 5]]
-3.0


In [8]:
#solve 
a = np.array([[3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
b = np.array([4, 2, 4, 2])
x=solve_triangular(a,b,lower=True)
print(x)
print(a.dot(x))

[ 1.33333333 -0.66666667  2.66666667 -1.33333333]
[4. 2. 4. 2.]


In [9]:
# linear equations solution
a = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
b = np.array([2, 4, -1])
x=linalg.solve(a,b)
print(x)

[ 2. -2.  9.]


In [11]:
A=np.array([[1,2],[3,4]])

In [12]:
la,v=linalg.eig(A)

In [13]:
l1,l2=la

In [15]:
print(l1,l2) #eigen values)

(-0.3722813232690143+0j) (5.372281323269014+0j)


In [17]:
print(v[:,0]) #first eigen vector

[-0.82456484  0.56576746]


In [19]:
A=[[1,2],[3,4]]
print(linalg.expm(A))

[[ 51.9689562   74.73656457]
 [112.10484685 164.07380305]]
